FROM mcr.microsoft.com/playwright:v1.55.0-noble

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        xvfb \
        x11vnc \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN npm ci

EXPOSE 4000
EXPOSE 7000

CMD ["npm", "start"]